### ISSUE TITLE
Small bug with bards

### ISSUE THREAD

**Issue by ACCoker** [FrozenOrb/HCTeams-Issues#10] opened 2016-06-14 03:22 UTC
After bards give speed 3 and it switches back to speed 2, if you don't reset your sprint, every 1-2 seconds your sprint will break for a split second, causing you to get slowed down. Here is an example https://youtu.be/JcMMtC17V6U
It's a bit difficult to notice just by watching in a vid, but it's very noticable in-game. This happens almost every time after the speed 3 wears off.

**Comment by TheRealGuru** [comment] 2016-06-14 08:47
Duplicate of #1, bug is being worked on.

**Closed by TheRealGuru** 2016-06-14 08:47 UTC
